---
apiVersion: compute.azure.upbound.io/v1beta1
kind: LinuxVirtualMachine
metadata:
  name: my-vm
spec:
  forProvider:
    location: eastus
    resourceGroupNameRef:
      name: dot-group
    size: Standard_A1_v2
    sourceImageReference:
      - offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS
        version: latest
    adminSshKey:
      - publicKey: ssh-rsa
          AAAAB3NzaC1yc2EAAAADAQABAAABAQC+wWK73dCr+jgQOAxNsHAnNNNMEMWOHYEccp6wJm2gotpr9katuF/ZAdou5AaW1C61slRkHRkpRRX9FA9CYBiitZgvCCz+3nWNN7l/Up54Zps/pHWGZLHNJZRYyAB6j5yVLMVHIHriY49d/GZTZVNB8GoJv9Gakwc/fuEZYYl4YDFiGMBP///TzlI4jhiJzjKnEvqPFki5p2ZRJqcbCiF4pJrxUQR/RXqVFQdbRLZgYfJ8xGB878RENq3yQ39d8dVOkq4edbkzwcUmwwwkYVPIoDGsYLaRHnG+To7FvMeyO7xDVQkMKzopTQV8AuKpyvpqu0a9pWOMaiCyDytO7GGN
          you@me.com
        username: adminuser
    adminUsername: adminuser
    osDisk:
      - caching: ReadWrite
        storageAccountType: Standard_LRS
    networkInterfaceIdsRefs:
      - name: dot-interface
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: dot-group
spec:
  forProvider:
    location: eastus
---
apiVersion: network.azure.upbound.io/v1beta1
kind: NetworkInterface
metadata:
  name: dot-interface
spec:
  forProvider:
    ipConfiguration:
      - name: my-vm
        privateIpAddressAllocation: Dynamic
        subnetIdRef:
          name: dot-subnet
    location: eastus
    resourceGroupNameRef:
      name: dot-group
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: dot-subnet
spec:
  forProvider:
    addressPrefixes:
      - 10.0.1.0/24
    resourceGroupNameRef:
      name: dot-group
    virtualNetworkNameRef:
      name: dot-network
---
apiVersion: network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: dot-network
spec:
  forProvider:
    addressSpace:
      - 10.0.0.0/16
    location: eastus
    resourceGroupNameRef:
      name: dot-group
