---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-password
  namespace: crossplane-system
data:
  password: cG9zdGdyZXM=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: my-db
spec:
  compositionSelector:
    matchLabels:
      provider: google
      db: postgresql
